# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajul.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from right_rep_final import right_rep
from left_rep_final import left_rep
from squats import squats

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 811, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("background.jpg"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(left_rep)
        self.pushButton.setGeometry(QtCore.QRect(490, 110, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #c7c7c7")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.clicked.connect(right_rep)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 210, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: #c7c7c7")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.clicked.connect(situp)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 310, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: #c7c7c7")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 20, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Romantic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(475, 355, 500, 61))
        font = QtGui.QFont()
        font.setFamily("Romantic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(475, 375, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Romantic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Left Reps"))
        self.pushButton_2.setText(_translate("MainWindow", "Right Reps"))
        self.pushButton_3.setText(_translate("MainWindow", "Squats"))
        self.label_2.setText(_translate("MainWindow", "FitTrackr"))
        self.label_3.setText(_translate("MainWindow", "PRESS 'r' TO RESET COUNTER"))
        self.label_4.setText(_translate("MainWindow", "PRESS 'q' TO EXIT"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
