'''
-*- coding: utf-8 -*-

 Form implementation generated from reading ui file 'gui.ui'

 Created by: PyQt5 UI code generator 5.15.9

 WARNING: Any manual changes made to this file will be lost when pyuic5 is
 run again.  Do not edit this file unless you know what you are doing.
 '''

# importing necessary modules and functions

from PyQt5 import QtCore, QtGui, QtWidgets
from right_rep_final import right_rep
from left_rep_final import left_rep
from situp import situp

class UiMainWindow:
    '''This class is for front end'''

    def __init__(self):
        self.centralwidget = None
        self.label = None
        self.push_button = None
        self.push_button_2 = None
        self.push_button_3 = None
        self.label_2 = None
        self.label_3 = None
        self.label_4 = None
        self.statusbar = None
    def setup_ui(self, main_window):
        '''This function setups main window'''
        main_window.setObjectName("MainWindow")
        main_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 811, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("background.jpg"))
        self.label.setObjectName("label")
        self.push_button = QtWidgets.QPushButton(self.centralwidget)
        self.push_button.clicked.connect(left_rep)
        self.push_button.setGeometry(QtCore.QRect(490, 110, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.push_button.setFont(font)
        self.push_button.setStyleSheet("background-color: #c7c7c7")
        self.push_button.setObjectName("push_button")
        self.push_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_2.clicked.connect(right_rep)
        self.push_button_2.setGeometry(QtCore.QRect(570, 210, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.push_button_2.setFont(font)
        self.push_button_2.setStyleSheet("background-color: #c7c7c7")
        self.push_button_2.setObjectName("push_button_2")
        self.push_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_3.clicked.connect(situp)
        self.push_button_3.setGeometry(QtCore.QRect(490, 310, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Nova")
        font.setPointSize(10)
        self.push_button_3.setFont(font)
        self.push_button_3.setAutoFillBackground(False)
        self.push_button_3.setStyleSheet("background-color: #c7c7c7")
        self.push_button_3.setObjectName("push_button_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 20, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Romantic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(475, 355, 500, 61))
        font = QtGui.QFont()
        font.setFamily("Romantic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(475, 375, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Romantic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white")
        self.label_4.setObjectName("label_4")
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        '''Retranslate the user interface elements of the main window.'''
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push_button.setText(_translate("MainWindow", "Left Reps"))
        self.push_button_2.setText(_translate("MainWindow", "Right Reps"))
        self.push_button_3.setText(_translate("MainWindow", "Squats"))
        self.label_2.setText(_translate("MainWindow", "FitTrackr"))
        self.label_3.setText(_translate("MainWindow", "PRESS 'r' TO RESET COUNTER"))
        self.label_4.setText(_translate("MainWindow", "PRESS 'q' TO EXIT"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
